### ISSUE TITLE
The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (2, 2).

### ISSUE THREAD

**Issue by MingsiWang** [kopper-xdu/Adv-Diffusion#13]
你好，装完环境后报错如下，请问应该如何解决
Traceback (most recent call last):
  File "eval.py", line 194, in <module>
    main(args)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "eval.py", line 106, in main
    c = model.cond_stage_model.encode(batch["txt"])
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/modules/encoders/modules.py", line 193, in encode
    return self(text)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/modules/encoders/modules.py", line 170, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/modules/encoders/modules.py", line 177, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/modules/encoders/modules.py", line 189, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/open_clip/transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/open_clip/transformer.py", line 250, in attention
    return self.attn(
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1275, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/wangms/anaconda3/envs/face/lib/python3.8/site-packages/torch/nn/functional.py", line 5438, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (2, 2).

**Comment by kopperx** [comment]
使用readme提供的conda环境安装方式

**Comment by MingsiWang** [comment]
按照readme安装环境后报错如下：
No module 'xformers'. Proceeding without it.
LatentInpaintDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.93 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
/home/wangms/anaconda3/envs/adv-diff/lib/python3.9/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Data shape for DDIM sampling is (2, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:34<00:00,  1.34it/s]
0 2
tensor([0.5410, 0.0832], device='cuda:0')
Data shape for DDIM sampling is (2, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:34<00:00,  1.35it/s]
1 2
tensor([0.1190, 0.1430], device='cuda:0')
Warning: Got 1 conditionings but batch-size is 2
Data shape for DDIM sampling is (2, 4, 64, 64), eta 1.0
Running DDIM Sampling with 46 timesteps
DDIM Sampler:   0%|                                                                                                                            | 0/46 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/wangms/face_recognition/Adv-Diffusion/eval.py", line 208, in <module>
    main(args)
  File "/home/wangms/anaconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wangms/face_recognition/Adv-Diffusion/eval.py", line 147, in main
    samples_cfg, intermediates = sampler.sample(
  File "/home/wangms/anaconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/models/diffusion/ddim.py", line 108, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "/home/wangms/anaconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/models/diffusion/ddim.py", line 169, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/home/wangms/anaconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/models/diffusion/ddim.py", line 218, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/wangms/anaconda3/envs/adv-diff/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangms/face_recognition/Adv-Diffusion/ldm/models/diffusion/ddpm.py", line 1337, in forward
    xc = torch.cat([x] + c_concat, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 2 for tensor number 1 in the list.

**Comment by kopperx** [comment]
前几个样本已成功运行了，你可以自己debug，代码经过验证没有问题，注意eval.sh中的注释

**Comment by MingsiWang** [comment]
我看issue中有人和我一样的问题，他是怎么解决的，请问你是如何成功运行的，我完全按照的你的readme进行，报错 Sizes of tensors must match except in dimension 1. Expected size 4 but got size 2 for tensor number 1 in the list.

**Comment by kopperx** [comment]
你可以问他一下，我这边没有任何报错
