### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 2 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by GeorgeCarpenter** [kopper-xdu/Adv-Diffusion#4]
After we run `bash eval.sh`, the following error occurred:
```
Traceback (most recent call last):
  File "/code/Adv-Diffusion/eval.py", line 194, in <module>
    main(args)
  File "/miniconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/Adv-Diffusion/eval.py", line 133, in main
    samples_cfg, intermediates = sampler.sample(
  File "/miniconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/Adv-Diffusion/ldm/models/diffusion/ddim.py", line 105, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "/miniconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/Adv-Diffusion/ldm/models/diffusion/ddim.py", line 166, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/miniconda3/envs/adv-diff/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/Adv-Diffusion/ldm/models/diffusion/ddim.py", line 215, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/code/Adv-Diffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/miniconda3/envs/adv-diff/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/code/Adv-Diffusion/ldm/models/diffusion/ddpm.py", line 1337, in forward
    xc = torch.cat([x] + c_concat, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 2 for tensor number 1 in the list.
```

**Comment by kopperx** [comment]
Are you sure you followed the README exactly?

**Comment by JohnCarpenter2** [comment]
> Are you sure you followed the README exactly?
Yes. 
Could you pack the code, enviroment, and datasets into a docker images? If you open-source the docker image, the open source community will benefit a lot from it.
@kopper-xdu

**Comment by kopperx** [comment]
I tried to configure the environment from scratch exactly according to the README, and I don't have the problem you described!
We will consider release a docker image later. Thank you for your advice.

**Comment by BiiiGerrr** [comment]
I have the same problem, how did you solve it

**Comment by MingsiWang** [comment]
I had the same problem as you. May I ask if your problem was solved and how it was solved
